### PR TITLE
Add broker support

### PR DESCRIPTION
**Pull request by neilcampbell**

### CODE REVIEW

**Comment by bethesque** [comment]
Can you rename `pactVersion` to `consumerVersion` please Neil? It's a subtle difference, but correctly naming that variable will help people understand the API and the underlying model a bit better.

**Comment by bethesque** [comment]
Especially where the interface is exposed to the user.

**Comment by neilcampbell** [comment]
@bethesque Yep sure can, nice catch. The param name was consumerVersion (so that's what is exposed to the user), I just named it badly in the test.

**Comment by neilcampbell** [comment]
And done.

**Comment by bethesque** [comment]
Cheers Neil.

**Pull request merged**
