### PR TITLE
Added an adhoc solution to cater for regex-validation

### PR DESCRIPTION
**Pull request by guruvn**
Added an adhoc solution to cater for regex-validation

### CODE REVIEW

**Comment by guruvn** [comment]
Below is an example of how the contract looks like in regards to the change
```json
{
  "provider": {
    "name": "HellowWorld APIs"
  },
  "consumer": {
    "name": "ReadonlyConsumer"
  },
  "interactions": [
    {
      "description": "The GET request mentioned above",
      "provider_state": "I have access to the given endpoint",
      "request": {
        "method": "get",
        "path": "/api/hello",
        "headers": {
          "Accept": "application/json; charset=utf-8",
          "CorrelationID": "9991600d-4c01-47c3-8ef1-cee84488c335"
        }
      },
      "response": {
        "status": 200,
        "headers": {
          "Content-Type": "application/json; charset=utf-8",
          "CorrelationID": "9991600d-4c01-47c3-8ef1-cee84488c335"
        },
        "body": {
          "Data": {
            "Content": "() => ^\\s*$"
          },
          "Meta": {
            "DateUtc": "() => ([0-2]\\d:[0-6]\\d:[0-6]\\d)?",
            "CorrelationId": "9991600d-4c01-47c3-8ef1-cee84488c335",
            "Code": 200
          }
        }
      }
    }
  ],
  "metadata": {
    "pactSpecificationVersion": "1.1.0"
  }
}
```

**Comment by neilcampbell** [comment]
Hi @guruvn!
That is quite an interesting approach, thanks for sending this through.
Unfortunately I will not be able to merge this into master, as it does not adhere to the [Pact Specification](https://github.com/pact-foundation/pact-specification/tree/version-2) for matching. The specification exists to try create some consistency across the different languages and allow Pacts generated in different languages to be verified correctly.

**Comment by guruvn** [comment]
Hi @neilcampbell ,

Fair enough, but feel free let me know if you need a hand on anything :)

**Comment by neilcampbell** [comment]
@guruvn I don't unfortunately. See https://github.com/SEEK-Jobs/pact-net/issues/9 for the conversation and context if you want to help out.

**Pull request closed without merging**
